/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/About.vue')['default']
    Batman: typeof import('./src/components/Batman.vue')['default']
    Calculator: typeof import('./src/components/Calculator.vue')['default']
    Calendar: typeof import('./src/components/calendar.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    Marquee: typeof import('./src/components/Marquee.vue')['default']
    MemberProfile: typeof import('./src/components/MemberProfile.vue')['default']
    Members: typeof import('./src/components/Members.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sample: typeof import('./src/components/Sample.vue')['default']
    Section1: typeof import('./src/components/Section1.vue')['default']
    Section2: typeof import('./src/components/Section2.vue')['default']
    Section3: typeof import('./src/components/Section3.vue')['default']
    UseMember: typeof import('./src/components/useMember.vue')['default']
  }
}
