/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/About.vue')['default']
    AdminDashboard: typeof import('./src/components/AdminDashboard.vue')['default']
    AdminProfileEdit: typeof import('./src/components/AdminProfileEdit.vue')['default']
    AdminSidebar: typeof import('./src/components/AdminSidebar.vue')['default']
    Batman: typeof import('./src/components/Batman.vue')['default']
    Calendar: typeof import('./src/components/calendar.vue')['default']
    Calendar_editor: typeof import('./src/components/calendar_editor.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    MemberProfile: typeof import('./src/components/MemberProfile.vue')['default']
    Members: typeof import('./src/components/Members.vue')['default']
    Mobile_dock: typeof import('./src/components/mobile_dock.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    Notes: typeof import('./src/components/Notes.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sample: typeof import('./src/components/Sample.vue')['default']
    Section1: typeof import('./src/components/Section1.vue')['default']
    Section2: typeof import('./src/components/Section2.vue')['default']
    Section3: typeof import('./src/components/Section3.vue')['default']
    UserCalEditor: typeof import('./src/components/userPanel/userCalEditor.vue')['default']
    UserDashboard: typeof import('./src/components/userPanel/UserDashboard.vue')['default']
    UserMobileDock: typeof import('./src/components/userPanel/userMobileDock.vue')['default']
    UserProfileEdit: typeof import('./src/components/userPanel/userProfileEdit.vue')['default']
    UserSideBar: typeof import('./src/components/userPanel/userSideBar.vue')['default']
    Violations: typeof import('./src/components/violations.vue')['default']
  }
}
